# .github/workflows/api.yml

name: Node.js API

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # or the desired Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    # Add any additional steps required for deployment, e.g., pushing Docker images, deploying to AWS, etc.
